global.EYES = [
  { id: "endrem:wither_eye", name: "Forgotten Eye", uiname:"§7Forgotten Eye"  },
  { id: "endrem:cursed_eye", name: "Cursed Eye", uiname:"§5Cursed Eye" },
  { id: "endrem:lost_eye", name: "Lost Eye", uiname:"§4Lost Eye" },
  { id: "endrem:magical_eye", name: "Lich Eye", uiname:"§bLich Eye"  },
  { id: "endrem:witch_eye", name: "Omen Eye", uiname:"§dOmen Eye" },
  { id: "endrem:exotic_eye", name: "Gilded Eye", uiname:"§3Gilded Eye"},
  { id: "endrem:cryptic_eye", name: "Cryptic Eye", uiname:"§aCryptic Eye"},
  { id: "endrem:old_eye", name: "Oblivion Eye", uiname:"§eOblivion Eye" },
  { id: "endrem:evil_eye", name: "Spy Eye", uiname:"§9Spy Eye" },
  { id: "endrem:corrupted_eye", name: "Corrupted Eye", uiname:"§2Corrupted Eye" },
  { id: "endrem:black_eye", name: "Black Eye", uiname:"§fBlack Eye"},
  { id: "endrem:nether_eye", name: "Infernal Eye", uiname:"§6Infernal Eye" }
];

global.FRAGMENT_TYPES = ['Core', 'Cracked', 'Shard']

global.REMOVE_ITEMS = [
  'cataclysm:mech_eye',
  'cataclysm:flame_eye',
  'cataclysm:void_eye',
  'cataclysm:monstrous_eye',
  'cataclysm:abyss_eye',
  'cataclysm:desert_eye',
  'cataclysm:cursed_eye',
  'endrem:cold_eye',
  'endrem:guardian_eye',
  'endrem:rogue_eye',
  'endrem:undead_eye',
  'apotheosis:potion_charm',
  'apotheosis:sigil_of_unnaming',
  'apotheosis:sigil_of_malice',
  'apothic_enchanting:infused_breath',
  'apotheosis:boss_summoner',
  'apothic_enchanting:hellshelf',
  'apothic_enchanting:infused_hellshelf',
  'apothic_enchanting:blazing_hellshelf',
  'apothic_enchanting:glowing_hellshelf',
  'apothic_enchanting:seashelf',
  'apothic_enchanting:infused_seashelf',
  'apothic_enchanting:crystal_seashelf',
  'apothic_enchanting:heart_seashelf',
  'apothic_enchanting:dormant_deepshelf',
  'apothic_enchanting:deepshelf',
  'apothic_enchanting:echoing_deepshelf',
  'apothic_enchanting:soul_touched_deepshelf',  
  'apothic_enchanting:echoing_sculkshelf',
  'apothic_enchanting:soul_touched_sculkshelf',
  'apothic_enchanting:endshelf',
  'apothic_enchanting:pearl_endshelf',
  'apothic_enchanting:draconic_endshelf',   
  'apothic_enchanting:beeshelf',
  'apothic_enchanting:melonshelf',
  'apothic_enchanting:stoneshelf',
  'apothic_enchanting:sightshelf',
  'apothic_enchanting:sightshelf_t2',
  'apothic_enchanting:treasure_shelf',
  'apothic_enchanting:geode_shelf',
  'apothic_enchanting:helmet_tome',
  'apothic_enchanting:chestplate_tome',
  'apothic_enchanting:leggings_tome',
  'apothic_enchanting:boots_tome',
  'apothic_enchanting:weapon_tome',
  'apothic_enchanting:bow_tome',
  'apothic_enchanting:pickaxe_tome',
  'apothic_enchanting:fishing_tome',
  'apothic_enchanting:other_tome',
  'apothic_enchanting:extraction_tome',
  'apothic_enchanting:scrap_tome',
  'apothic_enchanting:improved_scrap_tome',
  'apothic_enchanting:inert_trident',
  'apothic_enchanting:warden_tendril',
  'apothic_enchanting:flimsy_ender_lead',
  'apothic_enchanting:ender_lead',
  'apothic_enchanting:occult_ender_lead',

  'gamediscs:redstone_circuit', 
  'gamediscs:processor', 
  'gamediscs:battery', 
  'gamediscs:display', 
  'gamediscs:control_pad', 
  'irons_spellbooks:wayward_compass',
  'magic_coins:prosperity_amulet',

  'alshanex_familiars:illusionist_shard'
]

